name: Weekly UFC Fighter Database Update

on:
  workflow_dispatch:

  schedule:
    - cron: '0 4 * * 1'
jobs:
  run-batch-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the batch update script
        working-directory: ./backend
        run: python batch_update.py