name: Daily UFC Fighter Update

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  select-daily-fighter:
    runs-on: ubuntu-latest
    steps:
      - name: Select Daily Fighter
        run: |
          response=$(curl -s -X POST https://ufcdle.vercel.app/api/admin/select-daily)
          echo "Response: $response"

          # Check if the request was successful
          if echo "$response" | grep -q '"success":true'; then
            echo "✅ Daily fighter selected successfully"
            echo "$response" | grep -o '"fighter":"[^"]*"' | cut -d'"' -f4 | xargs -I {} echo "Selected fighter: {}"
            echo "$response" | grep -o '"bonus_stat":"[^"]*"' | cut -d'"' -f4 | xargs -I {} echo "Bonus stat: {}"
          else
            echo "❌ Failed to select daily fighter"
            echo "$response"
            exit 1
          fi
